### ISSUE TITLE
Incorrect referer

### ISSUE THREAD

**Issue by newmen** [igor-alexandrov/wiselinks#10]
Hello,

For business logic of my application has worked properly, I need to know which page user came from. For this purpose I use `request.referer`. But when I had started using wiselinks, I noticed that the referer wasn't set correct. It's set equal URL of final page, but not the page user came from.

**Comment by igor-alexandrov** [comment]
This is because Referrer header handling with AJAX calls. You can read a bit more about this here: http://stackoverflow.com/questions/1268673/set-request-header-in-javascript/1269064#1269064

Fixed in wiselinks-0.5.4.

Thanks for participating!

**Comment by newmen** [comment]
I already started to change wiselinks.js.coffee himself, but your solution is more inclusive.
Thank you very much for these quick fix of the problem.

**Comment by igor-alexandrov** [comment]
No problem!
