### ISSUE TITLE
Target and default content

### ISSUE THREAD

**Issue by pawel2105** [igor-alexandrov/wiselinks#13]
I'm not understanding the target replacement properly. Below is the rough layout of the rendered DOM on about every page:

```
body
  #container
    header
    .feed_container
    .sidebar
    .search_holder
    #dynamic_content
```

Every page has the div `#dynamic_content` but this is on template level, not in the layout. The layout is:

```
body
  #container
  header
    :yield
  footer
```

If I click any link with data-true then my header and footer disappear. How can I prevent this?

**Comment by igor-alexandrov** [comment]
How did you initialised Wiselinks object in application.js? Please paste code here.

**Comment by pawel2105** [comment]
Yes I did:

```
#application.js.coffee
//= require jquery
//= require jquery_ujs
//= require wiselinks
//= require_self
//= require_tree .

$(document).ready ->
    window.wiselinks = new Wiselinks()
```

I have tried moving the render header and render footer partials into each target template and this does work. This isn't great because the whole reason they were in the layout was to be DRY.

**Comment by pawel2105** [comment]
However, seeing as the de facto target is $('body') which encompasses the container that holds the header, footer and yielded content, I'm guessing I'm doing something wrong with the initialization...

:confused:

**Comment by igor-alexandrov** [comment]
By default Wiselinks replaces whole body to be as much compilant with Turbolinks as it can be.
To replace only `#dynamic_content` initialize it with proper params:

``` coffeescript
//= require jquery
//= require jquery_ujs
//= require wiselinks
//= require_self
//= require_tree .

$(document).ready ->
    window.wiselinks = new Wiselinks($('#dynamic_content'))
```

Also don't forger that you can change target for any link by defining `data-target` attribute:

``` html
<a href="http://example.com/path" data-target="#another_content" data-push="partial">special link</a>
```

**Comment by pawel2105** [comment]
I've played around with the initializer. It definitely does work, but if I specify a certain target, it recreates existing divs inside of the target div (i.e the target div will get another .sidebar div even one exists). This may be due to idiosyncrasies on my side. I'll close this for now and use the non-DRY method as that works for me. If I reproduce this problem in a barebones rails app, I'll re-open this ticket.

Thanks
:+1:
