### ISSUE TITLE
wiselink fails silently, when target-container is not present

### ISSUE THREAD

**Issue by mugwump** [igor-alexandrov/wiselinks#14]
I'm not sure, if this is simple an annoyance or an actual bug: When the target-container (either defined locally on the link form with data-target or globally in the setup) is not present, then wiselinks does not complain, but makes the call, and updates the non-existing container. Maybe this behavior should be configurable? It should be possible to either: 
- fail with an exception 
- only write a console.log-message
- do nothing silently (as it is right now)
- fall back to non-ajax-submit

if the target-container is not present. This would certainly help to see, if wiselink is set up correctly...

**Comment by igor-alexandrov** [comment]
I will implement this in next release. Thanks for idea!
The only problem is with console.log-message. As you know it is not always available, so I think that we should not use it. What do you think?

**Comment by mugwump** [comment]
the simple thing to do would be to check, if the console is available. The more elaborate thing to do would be using on the js-logging-frameworks (http://ajaxpatterns.org/Javascript_Logging_Frameworks) - although I'm not sure, if it is wise to introduce a dependency on on of these (and I'm not sure if any of these are any good/maintained/worth the effort...)- Or simply require an object that responds to .log in the configuration?!

**Comment by igor-alexandrov** [comment]
I've implemented exception raising in wiselinks-0.6.0. I am not sure all other options, but I will keep thinking about them.

Thanks!
