### ISSUE TITLE
HTTPS

### ISSUE THREAD

**Issue by phillyslick** [igor-alexandrov/wiselinks#15]
Hi, 

I'm getting a:

_Uncaught Error: SecurityError: DOM Exception 18_ 

when I try to navigate around a HTTPS site.  
I see that the X-Wiselinks-Url: is being sent as http://  - is that the issue?

Thanks.

**Comment by igor-alexandrov** [comment]
Thanks for reporting! I will look at this issue as soon as possible!

**Comment by phillyslick** [comment]
Thanks, I'll continue to check my code to see if it is something on my end.

**Comment by igor-alexandrov** [comment]
You forked it and tried to fix this issue here: https://github.com/phillyslick/wiselinks/commit/5248f1332a04af6ce8fff91b2502db342fa09f69

Did it help?

**Comment by phillyslick** [comment]
It did not.  The request X-Wiselinks-Referer is https://,
but the response X-Wiselinks-Url is http://

**Comment by phillyslick** [comment]
I have solved the problem.  It was in my nginx configuration, missing:
proxy_set_header X-Forwarded-Proto $scheme;

I'll check and see if it works without the modification I made to the gem.

**Comment by phillyslick** [comment]
Yeah it works fine, sorry for the false alarm.

Really appreciate the gem.

**Comment by igor-alexandrov** [comment]
No problem. Thanks for testing!
