### ISSUE TITLE
form params should be encoded

### ISSUE THREAD

**Issue by incubus** [igor-alexandrov/wiselinks#18]
Hi!

  I can't use form param with value like this "http://www.site.com/data.htm?stamp=2013.1.0.116.CaxH13&base=1007.77.0.0&id=9094497" because it's trimmed by _process_form function into "http://www.site.com/data.htm?stamp=2013.1.0.116.CaxH13"

I've tried to use escape function:

```
for key of params
  serialized.push("#{key}=#{escape(params[key])}")
```

But your line with replace(/%|!/g, '') function breaks my idea. :)

**Comment by igor-alexandrov** [comment]
Fixed in wiselinks-0.6.0.
Thanks!
