### ISSUE TITLE
Form process can't match empty select tags in jQuery 1.9.1 and high

### ISSUE THREAD

**Issue by faustman** [igor-alexandrov/wiselinks#19]
Hi!

I think selectors works bad.

``` javascript
$form.find(':input[value=""]:not(:disabled)')
```

Maybe should try through 'filter' function?

Prove:
jQuery 1.9.1: http://jsfiddle.net/junglecore/Keevt/
jQuery 1.8.3: http://jsfiddle.net/junglecore/Keevt/1/

**Comment by igor-alexandrov** [comment]
Yes, it seems to me that you are right and selectors in 1.9.1 does not work as expected.
I will try filter instead. Thanks.

**Comment by igor-alexandrov** [comment]
Fixed in wiselinks-0.6.0.
Thanks!
