### ISSUE TITLE
Please provide a standalone (without ruby) Version

### ISSUE THREAD

**Issue by Dexus** [igor-alexandrov/wiselinks#22]
Hello, can you please provide a standalone version?

Because i have problems to compilie the coffeescript... :( im new to cs and i dont have skills in ruby...

Thank You!

**Comment by igor-alexandrov** [comment]
Hello.
We added builder and compiler to make a standalone version to dev branch: https://github.com/igor-alexandrov/wiselinks/tree/dev

But we need some additional time (maybe a day or a couple) for testing.

**Comment by igor-alexandrov** [comment]
Done. Check build folder in repository.
