### ISSUE TITLE
Rails 2 support?

### ISSUE THREAD

**Issue by richarcher** [igor-alexandrov/wiselinks#24]
Any idea how to get this up and running with a Rails 2.3.x app? When booting after bundling the app crashes with `uninitialized constant Rails::Engine (NameError)` with the backtrace coming from `wiselinks-0.6.4/lib/wiselinks/rails.rb:3`

**Comment by igor-alexandrov** [comment]
Wow! I have never even imagine that Wiselinks can be useful in Rails 2 apps.
Basically you can use standalone version of Wiselinks (wiselinks.js) and write some Ruby code in your application to patch Request in the same way how it is done inside of Wiselinks.

I will try to rewrite initializer to make it work with Rails 2 when I have time.

**Comment by bnolan** [comment]
What happened with this - were any patches made?

**Comment by igor-alexandrov** [comment]
Sadly, but no.
I still didn't have enough time to make it work with Rails 2. The only thing that I know, that we have to rewrite initializer: include `Request` module into `ActionController::Request` instead of `ActionDispatch::Request`.
