### ISSUE TITLE
Control hashbang

### ISSUE THREAD

**Issue by waiting-for-dev** [igor-alexandrov/wiselinks#26]
I have noticed that an automatic hash is created for HTML4 browser. This is a great fallback, but the final URL for them is quite ugly because the id generated. It would be great if we could have some control over the hash generated, for example using a `data-hash` attribute.

**Comment by igor-alexandrov** [comment]
You can disable HTML4 support on Wiselinks initialization:

``` coffeescript
$(document).ready ->
    window.wiselinks = new Wiselinks($('body'), html4: false )
```

Isn't it what you want? In HTML4 browsers there is no other way to control state, but the hash.
Or I don't understand completely what you want?

**Comment by waiting-for-dev** [comment]
No, I don't want to disable HTML4 support. What I want, for example, is to have a link:

```
link_to "About", some_path, 'data-push' => true, 'data-hash' => 'about'
```

That generates a:

```
http://localhost:3000/#!about
```

insted of:

```
http://localhost:3000/#!about&suid=65326536263562
```

(I don't know exactly the fashion of the generated URL's. I don't have right now an HTML4 browser, I checked it yesterday).

Is it possible?

**Comment by igor-alexandrov** [comment]
We need `suid` anyway, because it stores current state of HTML history, that is emulated in Internet Explorer and other HTML4 browsers. `suid` is a key in a Hash that stores states.

**Comment by waiting-for-dev** [comment]
Ok, then there is not a lot we can do... thank you anyway!

**Comment by igor-alexandrov** [comment]
Done in 1.0.0 release, no more ugly `_suid`. Thanks to awesome History.js library.

**Comment by waiting-for-dev** [comment]
Thanks a lot!! :)
