### ISSUE TITLE
Partials

### ISSUE THREAD

**Issue by Dragsbaek** [igor-alexandrov/wiselinks#29]
I am trying to render at partial through wiselinks and get this error:

ActionView::MissingTemplate (Missing partial layouts/wiselinks with ...

I have this in my controller:

  def index
    @rooms = Room.all
    respond_to do |format|
      format.html # index.html.erb
      if self.request.wiselinks?
        render partial: "booking"
      end
    end
  end

**Comment by igor-alexandrov** [comment]
I will look at renderer code more deeply, but if you should not render partial on every wiselinks request. You should only render it on wiselinks_partial request. Look better at wiselinks demo application:
https://github.com/igor-alexandrov/wiselinks_example

**Comment by igor-alexandrov** [comment]
Did you find solution to your problem?

**Comment by Dragsbaek** [comment]
I had to change my layout, so i don't render partials anymore. I have another problem though - i have a remote form inside some content loaded with wiselinks, but i keeps processing as html instead of js. Not sure if it could be related to WL?

**Comment by igor-alexandrov** [comment]
You have some JS inside of `<script>` tag? Or not? Inline JS works perfect in Wiselinks.
