### ISSUE TITLE
Wiselinks doesn't work with default settings

### ISSUE THREAD

**Issue by JohnBat26** [igor-alexandrov/wiselinks#33]
Hi.
I have added wiselinks into Gemfile.
Done with bundle install.
and added next into my application.coffee:

``` coffeescript
#= require jquery
#= require jquery_ujs
#= require bootstrap
#= require modernizr
#= require jquery
#= require wiselinks
#= require_tree .

$(document).ready ->
  window.wiselinks = new Wiselinks()
```

Bu AJAX don't works by default, how in turbolinks.
Why?

**Comment by igor-alexandrov** [comment]
Hello,
please look at HTML section of README: https://github.com/igor-alexandrov/wiselinks#html

Wiselinks process links that have `'data-push'=true` attribute.

**Comment by JohnBat26** [comment]
Hmm. 
But I use simple-navigation gem.

**Comment by igor-alexandrov** [comment]
I think that simple-navigation support styling of elements: https://github.com/andi/simple-navigation/wiki/Styling

**Comment by igor-alexandrov** [comment]
And dont' forget that we have demo application:
- sources: https://github.com/igor-alexandrov/wiselinks_example
- online: http://wiselinks.herokuapp.com/
