### ISSUE TITLE
Subdirectory Launch equals Redirect to Main Domain Root Path

### ISSUE THREAD

**Issue by mkralla11** [igor-alexandrov/wiselinks#38]
Let me start off by saying I really like and appreciate what you've already completed in this gem. I am very impressed.

I found one quirk specifically regarding html4 browsers (...I no, I hate supporting old browsers too ;)

To replicate the problem:

Perform a subdirectory launch of a given rails app.
Then, use wiselinks on the subdirectory app.

For example: you have domain www.myrailsapp.com
your subdirectory launch url is: www.myrailsapp.com/other_rails_app

You will see in HTML5 browsers after load:
www.myrailsapp.com/other_rails_app

You will see in HTML4 browsers ( i.e. 7, 8 for example) after load for a split second:
www.myrailsapp.com/.#/other_rails_app

then immediate loading/redirect to:
www.myrailsapp.com

Obviously this won't be a top priority to fix ( if it's even possible ), I just thought I would point it out to you if you decided to make a 'gotchas' section of your wiki. ( I do realize you give an option to turn off wiselinks for HTML4, but I wasn't sure if this was the specific reason to do so). Thanks again for all your hard work!

**Comment by igor-alexandrov** [comment]
Hmmm, maybe just not to add `{ :data => { :push => true } }` to links that will follow to this second application?
Anyway this is quite strange error, I will try to find reasons why it works like this.

**Comment by denislavski** [comment]
The same issue can be reproduced with the demo app (at http://wiselinks.herokuapp.com/catalog?page=4) if you open it with IE8/IE9.

**Comment by igor-alexandrov** [comment]
It is not the same issue at all.
@mkralla11 says that he want to load another Rails application with History.push. This is technically unavailable (because it is really another application and it has different assets, layout and so on), so he should just remove 'data-push' => true from such links.

In demo app, this is path optimization, that can be turned off while Wiselinks initialization.

**Comment by mkralla11** [comment]
It's really not a huge concern to me now because I usually develop a new rails app as a subdirectory deployment so I can test new ideas and features before having to register a new url. I just changed over the symlink for the subdirectory deployed app to it's own url, and obviously now your gem works as expected.

But regarding the actual issue at hand, the rails app that had your gem installed was the subdirectory deployed app, so technically speaking it should be no different than using your gem on a regularly deployed app.

**I was not, at any point, trying to use your gem 'across' two separate apps, because that really makes no sense from a theoretical standpoint.**

My goal was to simply using it on one single application, which was the subdirectory app, and only within this app. So the issue still stands (but again, the only really reason to try to find a solution is to help other people using your gem in a subdirectory deployed app, because mine has moved to it's own url).

Thank you again for all your help on this :) I hope this all makes sense.

**Comment by igor-alexandrov** [comment]
Now got it! :)

**Comment by tlemens** [comment]
+1
