### ISSUE TITLE
Dynamic layout parts handling

### ISSUE THREAD

**Issue by waiting-for-dev** [igor-alexandrov/wiselinks#40]
I'm using wiselinks in a Rails application. I'm telling it to change the content of `#content` selector, which is what is returned by the `yield` statement.

The problem is that I have a language menu outside of `#content`. The items of this language menu are generated from the application layout through the following type of code:

```
li = link_to "English", url_for(locale: "en")
```

I can't see any easy way to manage that small portions of dynamic layout with wiselinks. I don't know if I am missing something... Of course I could use some custom javascript to change it when `page:done`, but this is an ugly workaround, because then I'm using two approaches to get the same result: the one in rails, and the one in javascript.

Is there an easy way to manage that situations?

Thank you.

**Comment by igor-alexandrov** [comment]
As I see, you are missing some basic concepts of how Wiselinks works. The basic idea is it is 'not to reload data that won't change'. This means that usually your assets won't change on every request, in some web apps toolbars or some trees won't change too. When you do pagination, then no data except to paginated data will change.

So if you have to update some links outside of `#content` then maybe it is better to change content of full `body`?

**Comment by waiting-for-dev** [comment]
But if I change full `body` content I as well change a lot of things that do not need to be changed, as the branding (with its images), the main menu, some banner, the colophon...

In my whole page there are only two pieces that need update: the `#content` and the `.lang_menu`. What I'm asking for is maybe similar to the functionality that `wiselinks_title()` offers but more generic, to be able to change small pieces out of the main piece changed by wiselinks. Something like:

```
wiselinks_update($('.lang_menu'), render 'shared/lang_menu')
```

How do you see it?

Thank you!!!

**Comment by igor-alexandrov** [comment]
Now I understand. Can you create some code example or pull request.
My general approach for this is that such things are very very application specific and it seems to me that everybody is able to do this better with Wiselinks JS events. But I may be wrong.

What do you think?

**Comment by waiting-for-dev** [comment]
I see your point. I agree that it is quite application specific, but I don't know if we could find a general approximation to overcome some common issues that can arise. I illustrate it with my example:

The problem I have is that it is a mess to update the language menu from `application.coffee.js`. As I told you, I would like to do something like:

```
$('.lang_menu').html("<%= render 'shared/lang_menu' %>") # in a wiselinks event
```

But, of course, I can't use `render` easily in `application.coffee.js` (maybe I could do some very ugly things to access to it) and I have to be very careful with the double quotes `"` in `shared/lang_menu` to not provoke a syntax error in javascript.

If, instead of `application.coffee.js`, I put this code in `wiselinks.html.erb` layout file, then I can use `render` without problems, but I still have the double quotes headache, besides I don't like writing javascript in a layout file.

Instead of using `render`, I could change the language menu with pure javascript. If I do it that way, sure I am in the field of application specific code, but I don't like this approach because I feel doing the same thing in two ways: changing the language menu with `render` in rails and with javascript for AJAX requests.

For that reason, I proposed a wiselinks solution analogous to `wiselinks_title`, but I'm not too sure how it should work. The one I proposed above (`wiselinks_update($('.lang_menu'), render 'shared/lang_menu')`) would work to change DOM content, but it wouldn't work, for example, to change an attribute value (the `lang` attribute for the `html` tag). Maybe it would deserve some attention, too, the updating of `head` elements besides `title`, like `description` or some `meta` used by facebook or others...

I will give it some more thought... About trying a pull request, I'm not too expert with javascript but I could try...

**Comment by igor-alexandrov** [comment]
So you want to send some data in HTTP headers (wiselinks_title works with headers)... so we should find out limit of length for headers and then we will be able to understand can we use them to transport some custom data or not.

Also you can do just an another AJAX call after Wiselinks page:done event to update your data. This should work too.

**Comment by waiting-for-dev** [comment]
About the HTTP headers... I think it would be an overuse... Here it is a [question in stackoverflow about header length](hhttp://stackoverflow.com/questions/1097651/is-there-a-practical-http-header-length-limit).

If I have time I will give some thought about the second AJAX call or whatever and try a pull request, but I don't promise anything because I don't have (of course) too much time...

Thank you @igor-alexandrov !!

**Comment by pawel2105** [comment]
Why don't you update the element that the lang menu and content are both children to?

**Comment by waiting-for-dev** [comment]
Because it contains other elements that remains the same, among them the branding which has CSS3 animation that maybe (I haven't tried) would look strange if its content is updated via AJAX.

**Comment by igor-alexandrov** [comment]
The best would be to update this element with additional AJAX request. I have several similar situations in my current project. For example, to update favourites counter after certain actions.
