### ISSUE TITLE
No request sent to server if url containing a hash(not hashbang)

### ISSUE THREAD

**Issue by billychan** [igor-alexandrov/wiselinks#43]
I met a problem when Wiselinks refused to send request to server. I found the reason is my links containing hash, like "http://localhost:3000/foo/123#bar". Then I removed the hash "#bar" and it works.

To verify this, I cloned wiselinks-example repo, manually changed the link in `iindex.html.slim` from `catelog_path` to `/catelog#bar`. Then the link stopped working - hashState changed, but no request sent to server.

I browsed source and could only find code related to hashbang `#!` but not hash. I can't figure out why. Any clues or suggestions? Thanks!

**Comment by billychan** [comment]
Looks like the reason is from History.js. A link with hash can't get fired in state, no matter main url changed or not.

**Comment by billychan** [comment]
This should no longer be an issue.

**Comment by igor-alexandrov** [comment]
Why so?

**Comment by billychan** [comment]
@igor-alexandrov, I don't think this could and should be the responsibility of Wiselinks alone, which depends on History.js. And the better practice is to avoid using hashtag when needing request to server. After all Wiselink is supposed to be integrated into server as a powerful Ajax tool, unlike Javascript MVC frameworks.
