### ISSUE TITLE
route issue with redirecting locale

### ISSUE THREAD

**Issue by rbinsztock** [igor-alexandrov/wiselinks#45]
Hi,

We have a problem with HTML4 browser and our routes.

i got 

scope "(:locale)", :locale => "/en-be|fr-be|nl-be|INTL|BE/" do
    match "/en-be(/_path)" => redirect { |params, req| URI::escape "/en/#{params[:path]}".chomp("/") + add_query(req.query_parameters) }
    match "/fr-be(/_path)" => redirect { |params, req| URI::escape "/fr/#{params[:path]}".chomp("/") + add_query(req.query_parameters) }
  end

so when we try to reload the same page, the browser HTML4 (IE9) go back to the homepage like the history is not saved, and come back to the correct page.

if i try to go directly to the right url like : 

dev.mysite.fr/fr/articles the page is loaded and he reload again the page by going to the home again and come back to the right url with 
dev.mysite.fr/#./articles .

it's not easy to debug i have try to remove all History.back into your wiselinks-1.1.2.js but it does not help. Of course if i disable wiselinks for HTML4 browser everything work fine.

**Comment by igor-alexandrov** [comment]
As I have already written in #20 try `html4_normalize_path: false` during Wiselinks initialisation. This will prevent you from additional redirects.

**Comment by shoaibmalik786** [comment]
html4_normalize_path: false where should i do this, can you please give me the syntax for this

**Comment by shoaibmalik786** [comment]
i am getting an error "Uncaught SyntaxError: Unexpected token : " when i use this in my app

**Comment by igor-alexandrov** [comment]
``` coffeescript
new Wiselinks('body', { html4_normalize_path: false })
```

something like this should work.

**Comment by shoaibmalik786** [comment]
should i give body here or target?

**Comment by igor-alexandrov** [comment]
You should initialize Wiselinks with element that you want to replace.
So `body` is only for example here.

**Comment by shoaibmalik786** [comment]
window.wiselinks = new Wiselinks($('#tab-content'), { html4_normalize_path: false })
i am using this code but i am still getting the same error with IE8 browser.
it automatically redirects to home page with url  : localhost:3000/#./items

**Comment by shoaibmalik786** [comment]
if you have another solution, sir please let me know as soon as possible.

**Comment by shoaibmalik786** [comment]
thank you so much sir, it is working fine now. :+1:

**Comment by igor-alexandrov** [comment]
No problem!

**Comment by hoenth** [comment]
Igor - Thank you for all your great work on this. I am having the same issue as shoaimalik786. I have modified the initialization of WiseLinks as he shows: window.wiselinks = new Wiselinks($('#main_container'), { html4_normalize_path: false }). Yet I am still being redirected to http://192.168.1.119:3000/#./en/baltimore/projects.

Was there another piece of information that you provided to shoaibmalik786 that is not part of this thread?

**Comment by igor-alexandrov** [comment]
Hello Tom,
No I didn't provide any other information to @shoaibmalik786. Can you add more info about your problem here?

Thanks.

**Comment by amnesia7** [comment]
I did wonder if it could be something to do with the `html4_root_path` being set as `'/'` if the wiselinks-enabled page is actually at a sub-level rather than at the root level of the website but no combination of setting `html4_root_path` and `html4_normalize_path` seemed to help.

Any ideas @igor-alexandrov or @shoaibmalik786 ? It would be a shame to resort to disabling for html4 browsers when it could/should work.

Thanks
