### ISSUE TITLE
handler for attribute "method" in forms and links

### ISSUE THREAD

**Issue by bell-101** [igor-alexandrov/wiselinks#5]
Please add this feature in a future release

**Comment by drakmail** [comment]
It will be very usefull.

**Comment by igor-alexandrov** [comment]
We have already discussed this with Pavel and understood that this feature is not needed at all. Can you please add example of code, where this is needed?

Thanks.

**Comment by drakmail** [comment]
With this migrating forms to wiselinks will be very seamless.

PS. At now I can't imagine, how better change my "POST" form to ajax-"GET" form.

**Comment by igor-alexandrov** [comment]
I think that the problem is in your way of using wiselinks. You should use wiselinks in forms that actually change URL after submit (different filters for example, they usually use GET). And of course these forms should be usable if you just copy/paste URL in browser.

In all other forms (that use POST and PUT) `:remote => true` will be enought.
Don't you think so?

**Comment by drakmail** [comment]
Yes, `remote: true` is good approach, but it little more difficult to implement, than simple POST form. If wiselinks will support regular POST-forms, it will be very easy migrate existing forms (with no changes in controller).

**Comment by igor-alexandrov** [comment]
Can you contact me via Skype (alexandrov-igor), we will talk a bit more about this issue?

**Comment by waiting-for-dev** [comment]
Hey, which are the conclusions you made? I would like to hear from the pitfalls of implement wiselinks in POST forms, if any. Thank you :)

**Comment by igor-alexandrov** [comment]
To be short, Wiselinks should only use GET to submit forms, because Wiselinks suggests that URL will change to perform request and URL only changes on GET requests.

All other requests can easily be done with `:remote => true`.

**Comment by waiting-for-dev** [comment]
Yeah, ok, thanks for the information!

**Comment by igor-alexandrov** [comment]
No problem.
