### ISSUE TITLE
Possible to not reload parts of html?

### ISSUE THREAD

**Issue by amnesia7** [igor-alexandrov/wiselinks#51]
I have an app that has one portion of the page that I don't want to reload each time because the `div` contains certain information and has javascript events assigned to it.

This `div` is surrounded by other `divs` that will need to be reloaded though.

```
#content
  div.header-section-to-be-updated
  div.main-area
    div.section-to-be-updated
    div.preserve-content
  div.footer-section-to-be-updated
```

Is it possible to tell `#content` to reload but not a particular `div` within `#content`?

Otherwise I'd need to tell wiselinks to reload all the partials around it separately somehow which I'd rather not do.

Thanks

**Comment by igor-alexandrov** [comment]
I think that have some misunderstanding here. Wiselinks will insert all data, that you have rendered in you App to html element which was configured as a target during Wiselinks initialization or to target that was specified with `data-target` attribute.

**Comment by amnesia7** [comment]
In that case I think I'll need to restructure my html so that I can put the parts to update together in one div and have the content to preserve in another and then position it using css instead.

**Comment by igor-alexandrov** [comment]
Yes.
