### ISSUE TITLE
Issue after back button clicked

### ISSUE THREAD

**Issue by amnesia7** [igor-alexandrov/wiselinks#53]
Hi,

I have an `index` page and a `show` page that both use the same `sub_level_layout` layout that extend the `application` layout.

```
layouts
- application
- sub_level_layout
```

`sub_level_layout` has a partial (`my_partial`) which is the part of the page that I would like to reload/update.

Here's the code I'm using:

```
def index
  ...
  if request.wiselinks_partial?
    render :partial => 'my_partial'
  else
    render :layout => 'sub_level_layout'
  end
end

def show
  ...
  if request.wiselinks_partial?
    render :partial => 'my_partial'
  else
    render :layout => 'sub_level_layout'
  end
end
```

This works fine for clicking through pages of results on the index page and also allows me to click the link for one of the results to go to the show page.

However, it fails if I load the index page, click one of the results to display the show page and then click the back button. It doesn't seem to know what to use to render the index page it just shows a blank page. I need it to just refresh the contents of the partial so that the index will be displayed again.

If I load the index page, click through to a different page (paging done using wiselinks as well), then click one of the results to display the show page and then click the back button it works fine.

It doesn't seem to like clicking the back button to go to the starting page (page initially loaded as html rather than via wiselinks) and only refreshing contents using a partial rather than the full screen.

When the page fails to load the headers for the fail request contain `X-Requested-With:XMLHttpRequest` and `X-Wiselinks:template`

Does that make sense?

Any ideas where I'm going wrong?

Thanks

**Comment by amnesia7** [comment]
@igor-alexandrov, does my issue make sense?

Is it related to this section somehow https://github.com/igor-alexandrov/wiselinks/blob/master/lib/wiselinks/rendering.rb#L17-L25 ?

Does it need to allow a partial to be rendered if template request received or something?

Col

**Comment by igor-alexandrov** [comment]
Have you looked at example application? https://github.com/igor-alexandrov/wiselinks_example
It also has pagination, like your example.

Can you take a look at this application and tell me what is the difference with your application?

Thanks!

**Comment by amnesia7** [comment]
Yes, I looked at that first @igor-alexandrov.

My issue relates to not wanting to reload the full layout when I press the back button after going from the initial index page to the show page because both pages use the same layout.

I just want to update the partial within the layout. 

It works fine if I click page 2 link on my index page, then click a link to the show page and then press the back button. 

It just seems to fail if pressing the back button it tries to go to the first page that was loaded.

Col

**Comment by igor-alexandrov** [comment]
Ok. got it now.
You should always reload full layout with back button navigation, because during your browsing layout on your page can change, so I just cannot be sure that content can be inserted correctly.

Here is a link to the code that adds this check https://github.com/igor-alexandrov/wiselinks/blob/master/lib/assets/javascripts/_page.js.coffee#L54.

**Comment by amnesia7** [comment]
Is there anyway I can override this (ruby, html, js) because I don't want to reload the full page again if I press back to the start page?

Col

**Comment by igor-alexandrov** [comment]
Then maybe you should not include such html parts in Wiselinks layout? And load links with Wiselinks normal (not partial) request?

**Comment by amnesia7** [comment]
Can you explain what you mean by a wiselinks normal request? Do you mean reload the page? 

Are you able to provide a gist or something of how to not include html parts in a Wiselinks layout and load links with Wiselinks normal request?

This section of my site is a store locator and it has a list of stores with a map showing where they are and the user can click on a store and the list area is "replaced/updated" with the store details while the map remains on the page but now just shows the location of the chosen store rather than all stores.

I don't want to show a list of stores next to a map that I've loaded and if the user presses the back button after viewing the details for a single store then it has to reload the page completely, map and all. 

I just want it to reload the list part.

**Comment by amnesia7** [comment]
Hi @igor-alexandrov, I was wondering if you had an answer to my https://github.com/igor-alexandrov/wiselinks/issues/53#issuecomment-30356135 above yet?

Thanks

**Comment by amnesia7** [comment]
I think I've got it working now by changing:

```
$(function() {
  window.wiselinks = new Wiselinks();
});
```

to

```
$(function() {
  window.wiselinks = new Wiselinks($('.stores-container'));
});
```

and for my controller:

```
def index
  ...
  if request.wiselinks_partial?
    render :partial => 'my_partial'
  else
    render :layout => 'sub_level_layout'
  end
end

def wiselinks_layout
  'my_partial_as_a_layout'
end

def show
  ...
  if request.wiselinks_partial?
    render :partial => 'my_partial'
  else
    render :layout => 'sub_level_layout'
  end
end
```

New layout - `my_partial_as_a_layout.html.erb`:

```
<%= render 'stores/my_partial' %>
```

I don't like the way it requires me to replicate my partial as a layout in my layouts folder.

I also don't like the fact that this set of pages for the store locator need a specific div to be set as the container for wiselinks to work with even though each of the links has a `data-target` attribute set as `'.stores-container'` anyway.

@igor-alexandrov, can you either explain why this is possibly correct or what's wrong with it if it is still not right.

Thanks

**Comment by igor-alexandrov** [comment]
Ok, let me try to explain how all this works.

When you initialize Wiselinks with default settings

```
$(function() {
  window.wiselinks = new Wiselinks();
});
```

then all content will be inserted in `body` element. But when you use links with `data-push=partial` and `data-target=some element` attributes you can easily change part of page, this can be very useful in pagination blocks.

When you initialize Wiselinks with jQuery selector, then all content by default will be inserted inside of this element.

```
$(function() {
  window.wiselinks = new Wiselinks($('.stores-container'));
});
```

 but you still can use `data-push=partial` links.

Overriding layouts is not something wrong at all. In our application we usually have special wiselinks layouts for every our general layout. These wiselinks layouts are rendered inside of common layouts.

**Comment by amnesia7** [comment]
I understand now, thanks.

Do you normally name any layouts specifically required for wiselinks any different (eg prefix them with `wiselinks_`) or put them in a `layout/wiselinks` folder?
Or do you just use them like normal layouts?
Or should I rename `my_partial_as_a_layout` as `wiselinks` so that it is used without needing to override the `wiselinks_layout` method?

I was just wondering if you used any best practice at times like these.

**Comment by amnesia7** [comment]
Nevermind, I've just called the layout/template file `wiselinks` so that I don't need to override the `wiselinks_layout` method.

Thanks for your help with this issue.

Col

**Comment by igor-alexandrov** [comment]
And that is how we do in our applications. So you found one of the best ways.
