### ISSUE TITLE
redirect_to using wiselinks?

### ISSUE THREAD

**Issue by Phifo** [igor-alexandrov/wiselinks#57]
There is a way to use the redirect_to with wiselinks?

**Comment by Phifo** [comment]
well, I handled this replacing the `redirect_to` for `render js: "wiselinks.load('uri')"` , I don't know if it is the best solution but it works.

**Comment by igor-alexandrov** [comment]
Hello, yes, now it is the best solution. I should include this in Wiselinks documentation.
