### ISSUE TITLE
can't make this work :(

### ISSUE THREAD

**Issue by mirzadelic** [igor-alexandrov/wiselinks#6]
Can anyone help me to make this work :(
I use sublime text 2 editor with coffeescript compile, and i compiled your coffee code.
Now i included, in this order: jquery, _history.adapter.jquery.js, _history.js, _json2.js, jquery.plugin1.js, jquery.plugin2.js, wiselinks.js, application.js.

application.js:

``` javascript
$(document).ready(function() {
  window.wiselinks = new Wiselinks($('body'));
  $(document).off('page:loading').on('page:loading', function(event, url, target, render) {
    return console.log("Wiselinks loading: " + url + " to " + target + " within '" + render + "'");
  });
  $(document).off('page:complete').on('page:complete', function(event, xhr, settings) {
    return console.log("Wiselinks page loading completed");
  });
  $(document).off('page:success').on('page:success', function(event, $target, status) {
    return console.log("Wiselinks status: '" + status + "'");
  });
  return $(document).off('page:error').on('page:error', function(event, data, status) {
    return console.log("Wiselinks status: '" + status + "'");
  });
});
```

and on link 'data-push="true"', and it doesn't work, what can be the problem ? :(
Btw, all these scripts are minified in one, with google minify.
Website is written in PHP.

Sometimes it works, but that is 1 in 10 times.

**Comment by igor-alexandrov** [comment]
I is better to see your html, but I have fixed one bug in wiselinks-0.4.2 that might be a reason. The problem was in html elements inside `<a>` tag.

Try to update, please.

**Comment by mirzadelic** [comment]
Getting error on page load
Chrome:

```
Uncaught TypeError: Cannot read property 'pushState' of undefined 
```

Firebug:

```
TypeError: History.emulated is undefined
```

on this line:

``` javascript
Wiselinks.prototype.enabled=function(){return!History.emulated.pushState||this.options.html4===true;};Wiselinks.prototype.load=function(url,target,render){if(render==null){render='template';}
```

**Comment by igor-alexandrov** [comment]
Load in this order please:  
jquery
json2
history
history.jquery
wiselinks

and then in Firebug please inspect History object and if you will get an error send be results of inspect.

Thanks.  

Igor Alexandrov
–––––––––––––––––––––––––––––––––––––––
+7 (910) 531-6049
igor.alexandrov@gmail.com
skype: alexandrov-igor
–––––––––––––––––––––––––––––––––––––––

**Comment by mirzadelic** [comment]
Yes, it works, it was my bad, i loaded _history.html4.js insteed of _history.js
I don't need to load this _history.html4.js at all ?

Thanks.

**Comment by igor-alexandrov** [comment]
If you want to have support of HTML4 browsers (IE8 and IE9) by emulating pushState in them then you need it. If not - then no.  
But if you won't load it, please don't forget to disable html4 on Wiselinks startup.

window.wiselinks = new Wiselinks($('body'), html4: false);  

Igor Alexandrov
–––––––––––––––––––––––––––––––––––––––
+7 (910) 531-6049
igor.alexandrov@gmail.com
skype: alexandrov-igor
–––––––––––––––––––––––––––––––––––––––

**Comment by mirzadelic** [comment]
It works now.
But i have question with loading scripts in each page, and 300, 302 redirect, that doesn't work.
Example: [Click here](http://eventill.com/calendar) and now click to logo(to get on homepage) there is google api included in container div, but it doesn't load with page when using wiselink, and "Add new event" will redirect you to login page, but doesn't work.
Any fix for that?
Thanks.
