### ISSUE TITLE
Wiselinks not loading new content

### ISSUE THREAD

**Issue by dumplingsol** [igor-alexandrov/wiselinks#63]
Hi,

I have no idea why it doesn't work. Would appreciate it if someone could take a look and see what I've missed.

I have included the plugin in the plugins.js at the bottom. jQuery is loaded.

Page:
http://hammr.co/5886358/12/projects.html

Try pressing the "menu"-icon in the top right, then press the link "Bajskorv".

Code:
<a href="bajskorv.html" data-push="true" data-target="#content">Bajskorv</a>

<div id="content"></div>

What did I miss?

**Comment by igor-alexandrov** [comment]
Do you use Rails or what?

**Comment by dumplingsol** [comment]
Yes but I'm not running my own rails app, I'm using http://hammerformac.com

**Comment by igor-alexandrov** [comment]
I don't see that Wiselinks is initialised. Please use anything like this in `application.js.coffee`:

``` coffeescript
#= require jquery
#= require wiselinks

$(document).ready ->
    window.wiselinks = new Wiselinks()
```
