### ISSUE TITLE
Wiselinks with anchor does not works

### ISSUE THREAD

**Issue by vandamon** [igor-alexandrov/wiselinks#69]
Wiselinks with anchor tag or the '#' attribute does not works. Is this is a flaw?

**Comment by igor-alexandrov** [comment]
This is well known problem of History.js, not Wiselinks.
Thanks.

**Comment by vandamon** [comment]
Thanks for the clarification!

**Comment by ericboehs** [comment]
Looking at History.js, I'm not seeing this problem anywhere. For example, try opening a console on a wiselinks page and running: `History.pushState(null, null, "#test_anchor");` Anchor seems to push fine.

Also I'm not seeing any documented cases of anchors not working in History.js (aside <IE9). Ideas?
