### ISSUE TITLE
Comparison table in docs

### ISSUE THREAD

**Issue by marczking** [igor-alexandrov/wiselinks#70]
It hasn't been easy to decide if I should use wiselinks or pjax.

While comparing both I noticed that `Assets change detection` is kinda possible with pjax, although you have to do it manually. See https://github.com/defunkt/jquery-pjax#layout-reloading.
Just wanted to point that out because your table says it is not possible ;)

And am I right if I assume you are doing it the exact same way, except automated?

All in all great job with this project! :+1:

**Comment by igor-alexandrov** [comment]
Thanks for this notice! Table can be a bit outdated :)

**Comment by igor-alexandrov** [comment]
Updated compare table.
