### ISSUE TITLE
IE8 support is brocken (again?)

### ISSUE THREAD

**Issue by mindreframer** [igor-alexandrov/wiselinks#76]
```
Object doesn't support this property or method
  //line 28: _dom_parser.js
  doc = document.implementation.createHTMLDocument('');
```

it seems that implemenation method is not present in IE8... any workarounds?

**Comment by igor-alexandrov** [comment]
Hello, I am at vacation now, will be able to fix this only after June, 20.

**Comment by mindreframer** [comment]
Ok, well then, have a nice vacation! see you next week!

**Comment by amnesia7** [comment]
Testing as IE8 I get this issue:

```
SCRIPT438: Object doesn't support property or method 'createHTMLDocument' 
_dom_parser.js, line 28 character 9
```

and testing as IE9 I get:

```
SCRIPT16389: Unspecified error. 
_dom_parser.js, line 29 character 9
```

line 28 and 29 are:

```
doc = document.implementation.createHTMLDocument('');
doc.open('replace');
```

Is there a reason for this?

Col

**Comment by mindreframer** [comment]
closing, because not relevant anymore (IE8 must die! ) :P
