### ISSUE TITLE
redirect still doesn't work

### ISSUE THREAD

**Issue by mirzadelic** [igor-alexandrov/wiselinks#8]
I can't make redirects work still, saw new version, but nothing changes on link..
Check out [here](http://eventill.com/) click on "Add new event".
Any solution ?

**Comment by igor-alexandrov** [comment]
Yes, I pushed some new code to wise links today, I cannot say that version 0.5.0 is fully completed, but it should work.  
To make redirects work properly you should follow two rules:
1) make proper redirects in your controller (proper status + location header). In Rails it is done with redirect_to method
2) send X-Wiselinks-Url header with current `request.url` value. Please check some Ruby code here https://github.com/igor-alexandrov/wiselinks/blob/master/lib/wiselinks/controller_methods.rb it is very easy to understand. This feature works exactly like in PJAX.

Igor Alexandrov
–––––––––––––––––––––––––––––––––––––––
+7 (910) 531-6049
igor.alexandrov@gmail.com
skype: alexandrov-igor
–––––––––––––––––––––––––––––––––––––––

**Comment by mirzadelic** [comment]
In PJAX i don't need to set header.
Thanks anyway, can't make it to work :/

**Comment by igor-alexandrov** [comment]
In PJAX you have to set header in order to make window.location change: https://github.com/defunkt/jquery-pjax/blob/master/jquery.pjax.js#L571

How do you try to do a redirect? what HTTP status to you return?

**Comment by mirzadelic** [comment]
"Refresh:0;url=http://www.example.com/page"

**Comment by igor-alexandrov** [comment]
Are you using meta tags for redirect like here: http://webmaster.iu.edu/tools-and-guides/maintenance/redirect-meta-refresh.phtml or what?

**Comment by mirzadelic** [comment]
Yes, it is like this..
It doesn't work on this way.

**Comment by igor-alexandrov** [comment]
Please use HTTP 302 status code for redirect or emulate redirect with JS like
<code>window.location = 'url'</code>
or
<code>wiselinks.load('url')</code>

The W3C discourage the use of meta refresh. Just follow standards and all will work as you expect it to work.

**Comment by mirzadelic** [comment]
It works now, but new problem, address is not changing, it just load that page but doesn't change url.
PJAX redirect on this action, wiselink load that page.
Try on same link.

**Comment by igor-alexandrov** [comment]
Of course it will not change location just after 30x response. Response is handled by jQuery internally and I cannot use it. That is why you should add a custom header to you responses (to every response of your server). I have already said this before.
In wiselinks `X-Wiselinks-Url` header is set, in PJAX – `X-PJAX-URL`.
Set `X-Wiselinks-Url` header to url of your response and you will get it to work. If you use Wiselinks with Rails, then you won't need to do anything, all will work out of the box.

**Comment by mirzadelic** [comment]
I don't need to set header for pjax, it worked on redirect that wiselinks didn't work.
Nevermind, thanks for this.
